[package]
name = "pico-override"
version = "0.1.0"
edition = "2024"

[dependencies]
# Custom rplidar protocol crate
rplidar = { path = "../rplidar", default-features = false }
bitter = { version = "0.9.0", default-features = false }
# Efficient and safe struct casting
bytemuck = { version = "1.25.0", default-features = false, features = ["derive", "min_const_generics", "must_cast"] }
# Brain communication
cobs = { version = "0.5.1", default-features = false, features = ["defmt"] }
crc = "3.4.0"
# Pico setup & peripheral interfacing
cortex-m-rt = "0.7.5"
embassy-executor = { version = "0.10.0", features = ["platform-cortex-m", "executor-thread", "defmt"] }
embassy-futures = { version = "0.1.2", features = ["defmt"] }
embassy-rp = { version = "0.10.0", features = ["rp235xa", "rt", "defmt", "critical-section-impl", "rom-func-cache", "intrinsics", "rom-v2-intrinsics", "boot2-w25q080", "binary-info", "time-driver"] }
embassy-time = { version = "0.5.1", features = ["defmt", "defmt-timestamp-uptime"] }
embedded-hal-async = { version = "1.0.0", features = ["defmt-03"] }
embassy-sync = { version = "0.8.0", features = ["defmt"] }
embedded-rpc = "0.2.0"
# General rust utilites
fixed = { version = "1.31.0", features = ["defmt"] }
static_cell = "2.1.1"
# Debugging/logging
defmt = "1.0.1"
defmt-embassy-usbserial = { version = "0.2.1", optional = true, features = ["buffersize-64"], default-features = false }
defmt-rtt = { version = "1.1.0", optional = true }
embassy-usb = { version = "0.5.0", features = ["defmt"], optional = true }
panic-probe = { version = "1.0.0", features = ["print-defmt"] }

[features]
# Expose features that define whether to use probe & debug pins for logging or to output over USB serial interface
default = ["usb"]
usb = ["dep:embassy-usb", "dep:defmt-embassy-usbserial"]
probe = ["dep:defmt-rtt"]
