[package]
name = "display-testing"
version = "0.1.0"
edition = "2024"

[dependencies]
buoyant.workspace = true
embedded-graphics.workspace = true
vexide-embedded-graphics.workspace = true
display = { path = "../" }
coprocessor = { path = "../../coprocessor" }
autons.workspace = true
vexide.workspace = true
embedded-touch = "0.3.0"
shrewnit.workspace = true
