[target.'cfg(target_os = "vexos")']
rustflags = [
    # Vexide
    "-Clink-arg=-Tvexide.ld",
    "-Ctarget-feature=+thumb-mode",
    "-Cforce-unwind-tables=no",
    "-Cforce-frame-pointers=yes",
    # Make getrandom use the custom backend
    "--cfg", "getrandom_backend=\"extern_impl\""
]

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["compiler-builtins-mem"]
